### ISSUE TITLE
** in search crashes backend

### ISSUE THREAD

**Issue by Mondei1** [ch-a-os/DocSort#89]
By writing `fo**bar` into the search bar leads to `SyntaxError` and makes the backend unresponsible.

**Comment by 720degreeLotus** [comment]
What syntax error exactly is thrown?^^

**Comment by Mondei1** [comment]
This is the error, sorry ^^
```
(node:4505) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /.**/: Nothing to repeat
    at new RegExp (<anonymous>)
    at /home/mondei1/Dokumente/Workspace/DocSort/backend/src/endpoints/searchDocuments.ts:82:36
    at step (/home/mondei1/Dokumente/Workspace/DocSort/backend/src/endpoints/searchDocuments.ts:32:23)
    at Object.next (/home/mondei1/Dokumente/Workspace/DocSort/backend/src/endpoints/searchDocuments.ts:13:53)
    at fulfilled (/home/mondei1/Dokumente/Workspace/DocSort/backend/src/endpoints/searchDocuments.ts:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:4505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4505) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
